### PR TITLE
Fix #48 Add Phone Number column to User table

### LINKED ISSUE #48: Add Phone Number field to User
Add a phone number field to the user in the database and the API.

Create a SQL alter script that adds this column to the User table for the existing tables.

### PR DESCRIPTION
**Pull request by Chris-Johnston**
Fix #48 Add Phone Number column to User table

Adds the alteration script for adding the PhoneNumber column to the User table.
This is in the required format to be used by Twilio.
Updates the usages of User to populate this value from the DB.

### CODE REVIEW

**Review by SaamIAm — COMMENTED** [review]
Approve with addition of tests

**Comment by Chris-Johnston** [comment]
@SaamIAm ready for re-review

**Review by SaamIAm — APPROVED** [review]
Looks good, nice thorough tests.

**Comment by Chris-Johnston** [comment]
Will merge after change is applied to DB.

**Pull request merged**
