### PR TITLE
Add a leaderboard page

### PR DESCRIPTION
**Pull request by Chris-Johnston**
Adds a barebones leaderboard page that shows the top 10 results, including the name, score, pet name, and timestamp.

### CODE REVIEW

**Review by SaamIAm — APPROVED** [review]
Looks good, what if there is a tie?

**Comment by Chris-Johnston** [comment]
That depends on implementation from #41 @anishprasad01

**Comment by anishprasad01** [comment]
The order is decided by the results of OFFSET-FETCH. However that SQL query would handle a tie is how it will be returned. I can do some exploration and make sure it's handled correctly

**Comment by Chris-Johnston** [comment]
Because that is out of scope of this PR, I think it should be dealt with separately.

**Pull request merged**
